# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('graduated', '已毕业'), ('drop-out', '退学')], max_length=64),
        ),
    ]
