# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20160508_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '已出版'), ('producing', '待出版'), ('forbidden', '禁书')], default='producing', max_length=32),
        ),
    ]
