# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20160503_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '主机组信息',
            },
        ),
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'IP信息',
            },
        ),
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'verbose_name_plural': '主机信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '项目经理'), (3, '管理员')], default=1),
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='group',
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IPInfo'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='service',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='group',
            field=models.ManyToManyField(to='cmdb.HostGroup'),
        ),
    ]
