# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20160509_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='group',
            new_name='groups',
        ),
    ]
