# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20160509_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IPInfo'),
        ),
    ]
