# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=2, upload_to='uploads', verbose_name='文章图片'),
            preserve_default=False,
        ),
    ]
