# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160602_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_index', '可以查看'), ('view_record_details', '可以查看详情'), ('change_record_details', '可以修改详情'), ('add_record', '可以添加'), ('delete_record', '可以删除')), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
