# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_Date',
            new_name='publication_date',
        ),
    ]
