# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorFailureStatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='fault_info',
            field=models.TextField(max_length=255, verbose_name='问题（故障）'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='memo',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
