# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorFailureStatistics', '0003_auto_20160531_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='fault_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
    ]
