# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lock_flag',
            field=models.BooleanField(default=False),
        ),
    ]
