# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20160503_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='service',
            field=models.IntegerField(choices=[(1, 'tomcat'), (2, 'MySQL'), (3, 'Nginx'), (4, 'FTP')]),
        ),
    ]
