# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160525_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[('LinuxL1', 'Linux中高级'), ('LinuxL2', 'Linux架构师'), ('Linux51', 'Linux中高级(51网络)'), ('LinuxL251', 'Linux中高级+架构合成班(51网络)'), ('PythonDevOps', 'Python自动化开发'), ('PythonFullStack', 'Python高级全栈开发'), ('PythonDevOps51', 'Python自动化开发(51网络)'), ('PythonFullStack51', 'Python全栈开发(51网络)'), ('BigDataDev', '大数据开发课程'), ('Cloud', '云计算课程')], max_length=64, verbose_name='课程名称'),
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='course_type',
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester')]),
        ),
    ]
