# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('create_date', models.TimeField(auto_now=True)),
                ('lock_flag', models.BooleanField()),
            ],
        ),
    ]
