# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20160502_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField()),
                ('service', models.IntegerField(choices=[(1, '研发'), (2, '测试'), (3, '运维')])),
                ('group', models.IntegerField(choices=[(1, '研发'), (2, '测试'), (3, '运维')])),
                ('state', models.IntegerField(choices=[(1, '在线'), (2, '下线')])),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
