# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgroup',
            options={'verbose_name': '群组', 'verbose_name_plural': '群组'},
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='bbs.UserProfile', verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='brief',
            field=models.CharField(max_length=255, verbose_name='群简介'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='max_members',
            field=models.IntegerField(default=200, verbose_name='最大成员数'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='bbs.UserProfile', verbose_name='群成员'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='name',
            field=models.CharField(max_length=64, verbose_name='群名'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='bbs.UserProfile', verbose_name='拥有者'),
        ),
    ]
